INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (0, 0, 'results received');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (0, 1, 'test required');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (0, 2, 'sample taken');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (0, 3, 'sample required');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (1, 0, 'admissions');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (1, 1, 'moving');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (1, 2, 'discharge');
INSERT INTO flag_sub_types(flag_type_id, flag_subtype_id, name) VALUES (1, 3, 'death');
INSERT INTO flag_types(id, name) VALUES (0, 'lab tests');
INSERT INTO flag_types(id, name) VALUES (1, 'transfers');
INSERT INTO flag_types(id, name) VALUES (2, 'hygiene');
INSERT INTO flag_types(id, name) VALUES (3, 'feeding');
INSERT INTO flag_types(id, name) VALUES (4, 'drugs');
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239736', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239737', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239737', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239737', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239737', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239737', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239738', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239738', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239738', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239738', '-1', 2, -1);
INSERT INTO flags(patient_id, status, created_timestamp, resolved_timestamp, flag_type_id, flag_subtype_id) VALUES ('MSF.TS.3', 'confirmed', '1413239738', '-1', 2, -1);
INSERT INTO patients(id, created_timestamp, status, given_name, family_name, assigned_location_zone_id, assigned_location_tent_id, assigned_location_bed, age_years, age_months, age_type, age_certainty, gender, important_information, pregnancy_start_timestamp, first_showed_symptoms_timestamp, movement, eating, origin_location, next_of_kin) VALUES ('MSF.TS.1', '1413245002', 'confirmed', 'Gil', 'de Witte', 1, 2, 39, 0, 7, 'months', 'certain', 'm', 'This baby needs his diaper replaced daily', null, '1413115257', 'no movement', 'yes', 'Kailahun, unknown', 'Mother Jodina Ramadoap');
INSERT INTO patients(id, created_timestamp, status, given_name, family_name, assigned_location_zone_id, assigned_location_tent_id, assigned_location_bed, age_years, age_months, age_type, age_certainty, gender, important_information, pregnancy_start_timestamp, first_showed_symptoms_timestamp, movement, eating, origin_location, next_of_kin) VALUES ('MSF.TS.2', '1413245003', 'confirmed', 'Gil', 'de Witte', 1, 2, 39, 0, 7, 'months', 'certain', 'm', 'This baby needs his diaper replaced daily', null, '1413115257', 'no movement', 'yes', 'Kailahun, unknown', 'Mother Jodina Ramadoap');
INSERT INTO patients(id, created_timestamp, status, given_name, family_name, assigned_location_zone_id, assigned_location_tent_id, assigned_location_bed, age_years, age_months, age_type, age_certainty, gender, important_information, pregnancy_start_timestamp, first_showed_symptoms_timestamp, movement, eating, origin_location, next_of_kin) VALUES ('MSF.TS.3', '1413245004', 'confirmed', 'Gil', 'de Witte', 1, 2, 39, 0, 7, 'months', 'certain', 'm', 'This baby needs his diaper replaced daily', null, '1413115257', 'no movement', 'yes', 'Kailahun, unknown', 'Mother Jodina Ramadoap');
INSERT INTO patients(id, created_timestamp, status, given_name, family_name, assigned_location_zone_id, assigned_location_tent_id, assigned_location_bed, age_years, age_months, age_type, age_certainty, gender, important_information, pregnancy_start_timestamp, first_showed_symptoms_timestamp, movement, eating, origin_location, next_of_kin) VALUES ('MSF.TS.4', '1413245005', 'confirmed', 'Gil', 'de Witte', 1, 2, 39, 0, 7, 'months', 'certain', 'm', 'This baby needs his diaper replaced daily', null, '1413115257', 'no movement', 'yes', 'Kailahun, unknown', 'Mother Jodina Ramadoap');
INSERT INTO patients(id, created_timestamp, status, given_name, family_name, assigned_location_zone_id, assigned_location_tent_id, assigned_location_bed, age_years, age_months, age_type, age_certainty, gender, important_information, pregnancy_start_timestamp, first_showed_symptoms_timestamp, movement, eating, origin_location, next_of_kin) VALUES ('MSF.TS.5', '1413245005', 'confirmed', 'Gil', 'de Witte', 1, 2, 39, 0, 7, 'months', 'certain', 'm', 'This baby needs his diaper replaced daily', null, '1413115257', 'no movement', 'yes', 'Kailahun, unknown', 'Mother Jodina Ramadoap');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (0, 0, 0, 'Triage T1 In', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (1, 0, 0, 'Suspsect Zone S1 In', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (0, 0, 1, 'Triage T1 Out', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (1, 0, 1, 'Suspect Zone S1 Out', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (2, 0, 0, 'Probable Zone P1 In', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (3, 0, 0, 'Confirmed Zone P1 In', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (2, 0, 1, 'Probable Zone P1 Out', 'abc-333-def-444-hij-555');
INSERT INTO portals(zone_id, tent_id, portal_id, name, mac) VALUES (3, 0, 1, 'Confirmed Zone P1 Out', 'abc-333-def-444-hij-555');
INSERT INTO tents(zone_id, tent_id, name, capacity) VALUES (0, 0, 'T1', 10);
INSERT INTO tents(zone_id, tent_id, name, capacity) VALUES (1, 0, 'S1', 10);
INSERT INTO tents(zone_id, tent_id, name, capacity) VALUES (2, 0, 'P1', 10);
INSERT INTO tents(zone_id, tent_id, name, capacity) VALUES (3, 0, 'C1', 10);
INSERT INTO zones(zone_id, name, capacity) VALUES (0, 'triage', 30);
INSERT INTO zones(zone_id, name, capacity) VALUES (1, 'suspect zone', 20);
INSERT INTO zones(zone_id, name, capacity) VALUES (2, 'probable zone', 20);
INSERT INTO zones(zone_id, name, capacity) VALUES (3, 'confirmed zone', 20);
INSERT INTO zones(zone_id, name, capacity) VALUES (4, 'mortuary', 20);
INSERT INTO zones(zone_id, name, capacity) VALUES (5, 'outisde', 20);
